In [1]:
import pandas as pd

In [2]:
#read file into a data frame
f = open('codon_usage.csv', 'r')
df = pd.read_csv(f)

C:\Users\mayam\AppData\Local\Temp\ipykernel_4776\2449211354.py:3: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

In [3]:
#parse out only columns labeled as 'rod' (rodents)
rodents_mit = df[df['Kingdom'] == 'rod']

#remove the mitocondrial DNA by using the DNAtype column
rodents = rodents_mit[rodents_mit['DNAtype'] == 0]

In [4]:
#limit the number of rodents and print out dataframe
rodents = rodents[:5]
rodents

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
12633,rod,0,10007,3175,Sciurus aberti,0.02614,0.04346,0.00315,0.01386,0.01417,...,0.00693,0.01165,0.00630,0.01764,0.03811,0.04661,0.03874,0.00031,0.00000,0.00346
12636,rod,0,10013,13348,Thomomys bottae,0.01349,0.04188,0.00637,0.01191,0.01626,...,0.01251,0.00000,0.00644,0.00000,0.01933,0.00000,0.02255,0.00000,0.00000,0.00322
12638,rod,0,10026,2833,Cricetinae,0.01483,0.03,0.00000,0.01412,0.00706,...,0.01447,0.01200,0.01518,0.01271,0.02400,0.01518,0.05154,0.00106,0.00071,0.00106
12639,rod,0,10029,153527,Cricetulus griseus,0.01957,0.02202,0.00637,0.01413,0.01318,...,0.01015,0.01014,0.01023,0.02463,0.02807,0.02837,0.04111,0.00061,0.00055,0.00115
12641,rod,0,10030,22059,Cricetulus longicaudatus,0.02067,0.01841,0.00694,0.01419,0.01423,...,0.00816,0.01324,0.01079,0.03210,0.02616,0.03405,0.03631,0.00082,0.00045,0.00082

In [5]:
#create directionary of amino acids and corresponding codons

aas = {'Phe': ['UUU','UUC'], 'Leu': ['UUA','UUG','CUU','CUC','CUA','CUG'], 'Ile': ['AUU','AUC','AUA'], 'Met': ['AUG'], 'Val': ['GUU','GUC','GUA','GUG'],
       'Ser': ['UCU','UCC','UCA','UCG','AGU','AGC'], 'Pro': ['CCU','CCC','CCA','CCG'], 'Thr': ['ACU','ACC','ACA','ACG'], 'Ala': ['GCU','GCC','GCA','GCG'], 
       'Tyr': ['UAU','UAC'], '***': ['UAA','UAG','UGA'], 'Trp': ['UGG'], 'His': ['CAU','CAC'], 'Gln': ['CAA','CAG'], 'Asn': ['AAU','AAC'], 'Lys': ['AAA','AAG'],
       'Cys': ['UGU','UGC'], 'Arg': ['CGU','CGC','CGA','CGG','AGA','AGG'], 'Gly': ['GGU','GGC','GGA','GGG'], 'Asp': ['GAU','GAC'], 'Glu': ['GAA','GAG']}

In [6]:
#check that all amino acids are in dictionary (20+stop = 21)
len(aas)

21

In [7]:
#check that all codons are included in dictionary (should be 64)
count = 0
for i in aas:
    count += len(aas[i])
print(count)

64

In [8]:
#check to confirm all values are actual codons. Will return a key error if there is a typo
for i in aas: 
    for j in aas[i]:
        s = rodents[j]

In [15]:
#standarize by amino acid

#loop through each animal
for animal in rodents['SpeciesName']:
    #loop through all amino acids
    for aa in aas:
        #initalize total percent of amino acid
        total = 0 
        #loop through codons and add up percentages
        for codon in aas[aa]:
            total += rodents[rodents['SpeciesName'] == animal][codon]
        
        #loop through codons, normalize by amino acid, and replace in data frame
        for codon in aas[aa]:
            rodents.loc[rodents['SpeciesName'] == animal,[codon]] =  (rodents[rodents['SpeciesName'] == animal][codon])/total

In [19]:
#print rodents to make sure it updated 
rodents

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
12633,rod,0,10007,3175,Sciurus aberti,0.375575,0.624425,0.033561,0.147667,0.150970,...,0.153863,0.258659,0.139876,0.316413,0.683587,0.546104,0.453896,0.082228,0.000000,0.917772
12636,rod,0,10013,13348,Thomomys bottae,0.243634,0.756366,0.036840,0.068880,0.094037,...,0.305793,0.000000,0.157419,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000
12638,rod,0,10026,2833,Cricetinae,0.330805,0.669195,0.000000,0.120129,0.060065,...,0.212388,0.176134,0.222809,0.346227,0.653773,0.227518,0.772482,0.374558,0.250883,0.374558
12639,rod,0,10029,153527,Cricetulus griseus,0.470546,0.529454,0.064683,0.143481,0.133834,...,0.192856,0.192666,0.194376,0.467362,0.532638,0.408319,0.591681,0.264069,0.238095,0.497835
12641,rod,0,10030,22059,Cricetulus longicaudatus,0.528915,0.471085,0.077794,0.159063,0.159511,...,0.160567,0.260527,0.212318,0.550978,0.449022,0.483940,0.516060,0.392344,0.215311,0.392344

In [20]:
def species_diff(species1,species2):
    # finds the difference between the codon bias of two species
    
    # step a counting value to 0
    diff = 0 
    #loop through all amino acids
    for aa in aas:
        #loop through all codons
        for codon in aas[aa]:
            #add the difference between the species codon bias squared 
            diff += (rodents[rodents['SpeciesName'] == species1][codon] - rodents[rodents['SpeciesName'] == species2][codon])**2
    
    #return the total difference between two speices
    return diff